#!/usr/bin/env bash
#
# Script to automatically generate LaTeX content inclusion files.
# Scans the content/ directory for .tex files and generates:
# - content/contentCollection.tex with \input statements
# - frame/AUTOGEN_includeonly.tex with \includeonly statement
#

set -e

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

CONTENT_DIR="$PROJECT_ROOT/content"
CONTENT_COLLECTION_FILE="$CONTENT_DIR/contentCollection.tex"
INCLUDEONLY_FILE="$PROJECT_ROOT/frame/AUTOGEN_includeonly.tex"

# Find all .tex files in content directory, excluding special files
# Sort them for consistent output
TEX_FILES=()
while IFS= read -r -d '' file; do
    # Get relative path from project root
    rel_path="${file#$PROJECT_ROOT/}"
    
    # Skip excluded files
    basename=$(basename "$file")
    if [[ "$basename" == "contentCollection.tex" ]] || [[ "$basename" == "abstract.tex" ]]; then
        continue
    fi
    
    TEX_FILES+=("$rel_path")
done < <(find "$CONTENT_DIR" -name "*.tex" -type f -print0 | sort -z)

# Generate content/contentCollection.tex
{
    echo "% This file is autogenerated. Do not edit it manually. Changes will be lost."
    for file in "${TEX_FILES[@]}"; do
        echo "\\input{$file}"
    done
} > "$CONTENT_COLLECTION_FILE" || { echo "ERROR: Failed to generate $CONTENT_COLLECTION_FILE"; exit 1; }

# Generate frame/AUTOGEN_includeonly.tex with better structure
{
    echo "% This file is autogenerated. Do not edit it manually. Changes will be lost."
    echo ""
    echo "% Files are organized by chapter/section for better readability."
    echo "% Each file is on its own line to make diffs and version control easier."
    echo ""
    
    if [ ${#TEX_FILES[@]} -gt 0 ]; then
        echo "\\includeonly{%"
        
        # Track previous directory for grouping
        prev_dir=""
        last_index=$((${#TEX_FILES[@]} - 1))
        
        for i in "${!TEX_FILES[@]}"; do
            file="${TEX_FILES[$i]}"
            # Get directory name for grouping
            current_dir=$(dirname "$file")
            
            # Add comment separator when directory changes
            if [ "$current_dir" != "$prev_dir" ] && [ -n "$prev_dir" ]; then
                echo "  %"
            fi
            
            # Add file with proper comma handling
            if [ $i -eq $last_index ]; then
                echo "  $file%"
            else
                echo "  $file,%"
            fi
            
            prev_dir="$current_dir"
        done
        
        echo "}"
    else
        echo "\\includeonly{}"
    fi
    
    echo ""
} > "$INCLUDEONLY_FILE" || { echo "ERROR: Failed to generate $INCLUDEONLY_FILE"; exit 1; }

echo "✓ Content includes generated successfully (${#TEX_FILES[@]} file(s))"
